export const SUPABASE_URL = "https://gfhagvqslxwerfuhdzcs.supabase.co";
export const SUPABASE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdmaGFndnFzbHh3ZXJmdWhkemNzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1MTIyNjEsImV4cCI6MjA2ODA4ODI2MX0.KaZhpLv-lBjHn3njsCwrdHjUS2AI3fzPntsh_fWyxS0";
